name: Xcode Workflow

on:
  push:
    branches: main
  workflow_dispatch:

env:
  SCHEME: demo-gh-actions-swift
  PROJECT: demo-gh-actions-swift.xcodeproj
  WORKSPACE: demo-gh-actions-swift.xcodeproj/project.xcworkspace
  ARCHIVE_PATH: build/demo-gh-actions-swift.xcarchive
  EXPORT_PATH: build/demo-gh-actions-swift.ipa
  CONFIGURATION: Release

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest
    env:
      DESTINATION: platform=iOS Simulator,name=iPhone 14,OS=16.2
      SDK: iphoneos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build (Unsigned)
        run: |
          xcodebuild build \
          -workspace $WORKSPACE \
          -scheme $SCHEME \
          -configuration $CONFIGURATION \
          -sdk ${{ env.SDK }} \
          -destination "${{ env.DESTINATION }}" \
          CODE_SIGNING_ALLOWED=NO
      - name: Test
        run: |
          xcodebuild test \
          -project $PROJECT \
          -scheme $SCHEME \
          -sdk ${{ env.SDK }} \
          -destination "${{ env.DESTINATION }}"
  archive:
    name: Archive
    runs-on: macos-latest
    needs: build
    env:
      DESTINATION: generic/platform=iOS
      SDK: iphoneos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Increment Build Number
        run: xcrun agvtool next-version -all
      - name: Build Archive
        run: |
          xcodebuild archive \
          -workspace $WORKSPACE \
          -scheme $SCHEME \
          -configuration $CONFIGURATION \
          -sdk ${{ env.SDK }} \
          -destination ${{ env.DESTINATION }} \
          -archivePath $ARCHIVE_PATH \
          CODE_SIGNING_ALLOWED=NO
      - name: Install Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.DISTRIBUTION_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # Create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/${{ vars.BUNDLE_ID }}.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
          EXPORT_OPTIONS_PLIST_PATH=IOS_EXPORT_OPTION_PLIST

          # Import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # Create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # Import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # Apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Create ExportOptions
        env:
          IOS_EXPORT_OPTIONS_PLIST_BASE64: ${{ secrets.IOS_EXPORT_OPTIONS_PLIST }}
        run: echo -n "$IOS_EXPORT_OPTIONS_PLIST_BASE64" | base64 --decode -o ExportOptions.plist
      - name: Sign Archive
        run: |
          xcodebuild \
          -exportArchive \
          -archivePath $ARCHIVE_PATH \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $EXPORT_PATH
      - name: Upload Archive
        uses: actions/upload-artifact@v3
        with:
          name: demo-gh-actions-swift
          path: build/demo-gh-actions-swift.ipa
  upload:
    name: Upload to App Store
    runs-on: macos-latest
    needs: archive
    environment: test-flight
    env:
      USERNAME: ${{ secrets.APPLE_USERNAME }}
      PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}
    steps:
      - name: Download Archive
        uses: actions/download-artifact@v3
        with:
          name: demo-gh-actions-swift
      - name: Upload to App Store
        run: |
          xcrun altool --upload-app --type ios -f demo-gh-actions-swift.ipa -u ${{ env.USERNAME }} -p ${{ env.PASSWORD }}
