name: Xcode Workflow

on:
  push:
    branches: xcode-workflow
  workflow_dispatch:

env:
  SCHEME: demo-gh-actions-swift
  WORKSPACE: demo-gh-actions-swift.xcodeproj/project.xcworkspace
  ARCHIVE_PATH: demo-gh-actions-swift.xcarchive

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - run: |
          xcodebuild -workspace $WORKSPACE \
          -scheme $SCHEME \
          -configuration Release \
          -sdk iphoneos \
          -destination 'generic/platform=iOS' \
          build
