name: Xcode Workflow

on:
  push:
    branches: xcode-workflow
  workflow_dispatch:

env:
  SCHEME: demo-gh-actions-swift
  WORKSPACE: demo-gh-actions-swift.xcodeproj/project.xcworkspace
  ARCHIVE_PATH: demo-gh-actions-swift.xcarchive
  EXPORT_PATH: demo-gh-actions-swift.ipa

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      DESTINATION: generic/platform=iOS
      SDK: iphoneos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build (No Codesign)
        run: |
          xcodebuild -workspace $WORKSPACE \
          -scheme $SCHEME \
          -configuration Release \
          -sdk ${{ env.SDK }} \
          -destination ${{ env.DESTINATION }} \
          -archivePath $ARCHIVE_PATH \
          CODE_SIGNING_ALLOWED=NO \
          build
      - name: Create ExportOptions.plist
        run: |
          echo '<?xml version="1.0" encoding="UTF-8"?>' >> ExportOptions.plist
          echo '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">' >> ExportOptions.plist
          echo '<plist version="1.0">' >> ExportOptions.plist
          echo '<dict>' >> ExportOptions.plist
          echo '  <key>method</key>' >> ExportOptions.plist
          echo '  <string>app-store</string>' >> ExportOptions.plist
          echo '  <key>teamID</key>' >> ExportOptions.plist
          echo "  <string>${{ secrets.TEAM_ID }}</string>" >> ExportOptions.plist
          echo '</dict>' >> ExportOptions.plist
          echo '</plist>' >> ExportOptions.plist
      - name: Sign Archive
        run: |
          xcodebuild -exportArchive -archivePath $ARCHIVE_PATH \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $EXPORT_PATH \
          -allowProvisioningUpdates



