name: Xcode Workflow

on:
  push:
    branches: xcode-workflow
  workflow_dispatch:

env:
  SCHEME: demo-gh-actions-swift
  WORKSPACE: demo-gh-actions-swift.xcodeproj/project.xcworkspace
  ARCHIVE_PATH: build/demo-gh-actions-swift.xcarchive
  EXPORT_PATH: build/demo-gh-actions-swift.ipa
  CONFIGURATION: Release

jobs:
  build:
    name: Build & Test
    runs-on: macos-latest
    env:
      DESTINATION: platform=iOS Simulator,name=iPhone 14,OS=16.2
      SDK: iphoneos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build (Unsigned)
        run: |
          xcodebuild -workspace $WORKSPACE \
          -scheme $SCHEME \
          -configuration $CONFIGURATION \
          -sdk ${{ env.SDK }} \
          -destination "${{ env.DESTINATION }}" \
          CODE_SIGNING_ALLOWED=NO \
          build
      # - name: Test
      #   run: |
      #     xcodebuild test -workspace $WORKSPACE \
      #     -scheme $SCHEME \
      #     -sdk ${{ env.SDK }} \
      #     -destination "${{ env.DESTINATION }}"
  archive:
    name: Archive
    runs-on: macos-latest
    needs: build
    env:
      DESTINATION: generic/platform=iOS
      SDK: iphoneos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Archive
        run: |
          xcodebuild archive -workspace $WORKSPACE \
          -scheme $SCHEME \
          -configuration $CONFIGURATION \
          -sdk ${{ env.SDK }} \
          -destination ${{ env.DESTINATION }} \
          -archivePath $ARCHIVE_PATH \
          CODE_SIGNING_ALLOWED=NO
      - name: Install Distribution Certificate
        run: |
          echo ${{ secrets.DISTRIBUTION_CERTIFICATE }} | base64 --decode > /tmp/certificate.p12
          security create-keychain -p "" build.keychain
          security import /tmp/certificate.p12 -t agg -k ~/Library/Keychains/build.keychain -P ${{ secrets.DISTRIBUTION_CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain
          security unlock-keychain -p "" ~/Library/Keychains/build.keychain
      - name: Install Provisioning Profile
        run: |
          echo ${{ secrets.PROVISIONING_PROFILE }} | base64 --decode > /tmp/profile.mobileprovision
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp /tmp/profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
      - name: Sign Archive
        run: |
          xcodebuild -exportArchive -archivePath $ARCHIVE_PATH \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $EXPORT_PATH \
          -allowProvisioningUpdates
