name: Xcode Workflow

on:
  push:
    branches: xcode-workflow
  workflow_dispatch:

env:
  SCHEME: demo-gh-actions-swift
  WORKSPACE: demo-gh-actions-swift.xcodeproj/project.xcworkspace
  ARCHIVE_PATH: demo-gh-actions-swift.xcarchive

jobs:
  build:
    name: Build
    runs-on: macos-latest
    env:
      DESTINATION: generic/platform=iOS
      SDK: iphoneos
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build (No Codesign)
        run: |
          xcodebuild -workspace $WORKSPACE \
          -scheme $SCHEME \
          -configuration Release \
          -sdk ${{ env.SDK }} \
          -destination ${{ env.DESTINATION }} \
          -archivePath $ARCHIVE_PATH \
          CODE_SIGNING_ALLOWED=NO \
          build
